# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By 
# starting #with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find # the sum of the even-valued terms.

def last_two_indexs_sum input
  input[-1] + input[-2]
end

def fib_series_sum_generator max_value
  fib_series = [1,2]

  while fib_series.last < max_value
    break if last_two_indexs_sum(fib_series) > max_value
    fib_series << last_two_indexs_sum(fib_series)
  end
  
  fib_series.select { |num| num%2 == 0 }.sum
end

p fib_series_sum_generator 40_00_000
p fib_series_sum_generator 100